apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "webserver-hello-chart.fullname" . }}
spec:
  host: 
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "webserver-hello-chart.fullname" . }}
    weight: 100
  wildcardPolicy: None
