apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: myweb
  version: "1.0"
commonAnnotations:
  supportContact: support@example.com
resources:
- webserver.yaml
- webserver-service.yaml
- webserver-route.yaml
