apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-db
bases:
  - ../../base
# patchesStrategicMerge is deprecated
#patchesStrategicMerge:
#  - mydb-patch-limit-env.yaml 
patches:
  - path: mydb-patch-limit-env.yaml
    target:
      kind: Deployment
      name: mydb
    options:
      allowNameChange: true
