apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: newnetwork
  # Using default namespace so that this network can be used
  # by other projects 
  namespace: default
spec:
  config: |- 
      {
        "cniVersion": "0.3.1",
        "name": "hostdev-net",
        "type": "host-device",
        "device": "ens4",
        "ipam": {
           "type": "static"
        }
      }
    
