apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "newnetwork", "namespace": "default" , "ips": [ "192.168.51.10/24" ] } ]'
  labels:
    run: test1
  name: test1
spec:
  containers:
  - image: quay.io/bkthong/webserver-hello-ocp:1.1
    imagePullPolicy: Always
    name: test1
