apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "newnetwork", "ips": [ "192.168.51.10/24" ] } ]'
  labels:
    run: test2
  name: test2
spec:
  containers:
  - image: quay.io/bkthong/webserver-hello-ocp:1.2
    imagePullPolicy: Always
    name: test2
