apiVersion: v1
kind: ResourceQuota
metadata:
  name: myquota
spec:
  hard:
#    count/deployment: "5"        #this is wrong
#    count/deployment.apps: "5"   #this is also wrong
    count/deployments.apps: "5"   #this is correct
    count/pods: "10"
    requests.cpu: 2
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 1Gi
