apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: "hr-"
nameSuffix: "-001"
commonLabels:
  app: hrdb
  version: "1.0"
commonAnnotations:
  supportContact: support@example.com
resources:
- mydb.yaml
- mydb-service.yaml
